version: "3.8"

networks:
  spp_network:
    driver: bridge

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_automation
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Jakarta
      - METRICS_ENABLED=false
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - spp_network
    depends_on:
      - 9router
    restart: unless-stopped

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spp_sekolah
      POSTGRES_USER: spp_user
      POSTGRES_PASSWORD: ganti_password_ini
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  n8n_data:
  postgres_data:
